# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=1.0
group=me.autobot.elytramace
java_version=21

# Common
minecraft_version=1.21.11
mod_name=ElytraMace
mod_author=Kenzo101 & johsar
mod_id=elytramace
license=ARR
credits=
description=This mod allows you to Elytra-Mace while flying with the elytra!.
inecraft_version_range=[1.21.11,1.21.12)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=CHECK_LATEST
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.11
# https://parchmentmc.org/docs/getting-started#choose-a-version
parchment_version=CHECK_LATEST  

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_minecraft_version=1.21.11
fabric_loader_version=0.18.4
loom_version=1.14-SNAPSHOT
yarn_mappings=1.21.10+build.3

# Fabric API
fabric_api_version=0.141.4+1.21.11

# Forge, see https://files.minecraftforge.net/net/minecraftforge/forge/ for new versions
forge_version=60.0.0
forge_loader_version_range=[51.0.0,60.0.0)

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=[21.11.0-beta,21.11.46)
neoforge_loader_version_range=[21.11.46,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

org.gradle.java.home=/home/kenzo101/.jdks/ms-21.0.9
